"""initial_schema

Revision ID: fdc7ebcadb77
Revises: 
Create Date: 2026-04-09 23:53:32.967905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc7ebcadb77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bali_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('last_scan', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bali_chats_chat_id'), 'bali_chats', ['chat_id'], unique=True)
    op.create_table('place_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=True),
    sa.Column('mentioned_name', sa.String(), nullable=True),
    sa.Column('chat_title', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_reviews_place_name'), 'place_reviews', ['place_name'], unique=False)
    op.create_table('scraped_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_date', 'scraped_events', ['category', 'event_date'], unique=False)
    op.create_index(op.f('ix_scraped_events_event_date'), 'scraped_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_scraped_events_link'), 'scraped_events', ['link'], unique=False)
    op.create_index(op.f('ix_scraped_events_status'), 'scraped_events', ['status'], unique=False)
    op.create_index(op.f('ix_scraped_events_text_hash'), 'scraped_events', ['text_hash'], unique=True)
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_actions_action'), 'user_actions', ['action'], unique=False)
    op.create_index(op.f('ix_user_actions_telegram_id'), 'user_actions', ['telegram_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('agreed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_actions_telegram_id'), table_name='user_actions')
    op.drop_index(op.f('ix_user_actions_action'), table_name='user_actions')
    op.drop_table('user_actions')
    op.drop_index(op.f('ix_scraped_events_text_hash'), table_name='scraped_events')
    op.drop_index(op.f('ix_scraped_events_status'), table_name='scraped_events')
    op.drop_index(op.f('ix_scraped_events_link'), table_name='scraped_events')
    op.drop_index(op.f('ix_scraped_events_event_date'), table_name='scraped_events')
    op.drop_index('idx_category_date', table_name='scraped_events')
    op.drop_table('scraped_events')
    op.drop_index(op.f('ix_place_reviews_place_name'), table_name='place_reviews')
    op.drop_table('place_reviews')
    op.drop_index(op.f('ix_bali_chats_chat_id'), table_name='bali_chats')
    op.drop_table('bali_chats')
    # ### end Alembic commands ###
